//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C43QLXeKhach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENXE
    {
        public int MaChuyen { get; set; }
        public Nullable<System.DateTime> NgayKH { get; set; }
        public Nullable<System.DateTime> NgayDen { get; set; }
        public Nullable<int> MaTuyen { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<int> MaTX { get; set; }
        public Nullable<int> createUser { get; set; }
        public Nullable<int> lastupdateUser { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastupdateDate { get; set; }
        public Nullable<int> isDeleted { get; set; }
    }
}
