//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C43QLXeKhach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHAOSAT
    {
        public int MaKS { get; set; }
        public Nullable<System.DateTime> NgayKS { get; set; }
        public Nullable<int> NguoiKS { get; set; }
        public string DiaChiKS { get; set; }
        public Nullable<double> TiLeDonKhach { get; set; }
        public Nullable<decimal> GiaKS { get; set; }
        public Nullable<int> createUser { get; set; }
        public Nullable<int> lastupdateUser { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> lastupdateDate { get; set; }
        public Nullable<int> isDeleted { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
