//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C43QLXeKhach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ve
    {
        public int MaVe { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
        public Nullable<int> MaGhe { get; set; }
        public Nullable<System.DateTime> GioDi { get; set; }
        public string TenKH { get; set; }
        public string SDT { get; set; }
        public string TramLen { get; set; }
        public string TramXuong { get; set; }
        public string BienSoXe { get; set; }
        public string TenLoai { get; set; }
    }
}
